# Replace all dockertest fields 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dockertest-hpa
  namespace: dockertest
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: dockertest
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 65